proxy coap
absmach/mgate pull request #43
Opened 2023-10-03 12:07 UTC by SammyOina

Signed-off-by: SammyOina <sammyoina@gmail.com>

Pull request title should be `MF-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](https://github.com/mainflux/mainflux/blob/master/CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?

### Which issue(s) does this PR fix/relate to?
Put here `Resolves #XXX` to auto-close the issue that your PR fixes (if such)

### List any changes that modify/break current functionality

### Have you included tests for your changes?

### Did you document any new/modified functionality?

### Notes

2023-10-24 16:03 UTC, dborovcanin requested changes

2023-10-24 16:03 UTC, dborovcanin commented on pkg/coap/coap.go
> +	p.logger.Debug(fmt.Sprintf("Got message path=%v: %+v from %v", path, r, w.Conn().RemoteAddr()))
Remove this log.

2023-10-24 16:03 UTC, dborovcanin commented on pkg/coap/coap.go
> +		obs, err := r.Options().Observe()
Handle error first.

2023-10-24 16:03 UTC, dborovcanin commented on pkg/coap/coap.go
> +func (p *Proxy) handler(w mux.ResponseWriter, r *mux.Message) {
This method is too complex, consider creating separate methods for handling different status codes.

2023-10-24 16:35 UTC, SammyOina commented on pkg/coap/coap.go
> +		if err := sendErrorMessage(w.Conn(), r.Token(), err, codes.Unauthorized); err != nil {
this is for the case of error messages so not good to defer but return on occurrence

2025-09-16 15:41 UTC, dborovcanin commented
Replaced by https://github.com/absmach/mgate/pull/108.

2025-09-16 15:41 UTC, closed without merging