MPX-24 - Add support for CoAP and DTLS
absmach/mgate pull request #60
Opened 2024-04-12 07:46 UTC by 1998-felix

Pull request title should be `MF-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](https://github.com/absmach/magistrala/blob/master/CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?
This is a feature as it adds coap proxy support without TLS as well as DTLS temination for CoAP messaging.

### Which issue(s) does this PR fix/relate to?
 `Resolves #24` 

### List any changes that modify/break current functionality
No
### Have you included tests for your changes?
No
### Did you document any new/modified functionality?
No
### Notes

2024-04-19 11:00 UTC, rodneyosodo requested changes

2024-04-19 11:00 UTC, rodneyosodo commented on pkg/coap/coap.go
> +	event  session.Handler
```suggestion
	session  session.Handler
```

2024-04-19 11:00 UTC, rodneyosodo commented on pkg/coap/coap.go
> +func New(config mproxy.Config, handler session.Handler, logger *slog.Logger) *Proxy {
New is a go keyword. Let's rename it to something like

```suggestion
func NewProxy(config mproxy.Config, handler session.Handler, logger *slog.Logger) *Proxy {
```

2024-04-19 11:00 UTC, rodneyosodo commented on pkg/tls/tls.go
> +// Load returns a DTLS configuration that can be used in DTLS servers.
Fix godoc

2024-04-19 11:00 UTC, rodneyosodo commented on pkg/tls/tls.go
> +func LoadDTLS(c *Config) (*dtls.Config, error) {
Since Load and LoadDTLS are almost similar can we keep the code DRY?

2024-04-19 11:00 UTC, rodneyosodo commented on pkg/coap/coap.go
> +			}
return after

2024-04-22 14:35 UTC, 1998-felix commented on pkg/tls/tls.go
> +func LoadDTLS(c *Config) (*dtls.Config, error) {
I have refactored. Kindly check.

2024-04-25 08:02 UTC, rodneyosodo commented on pkg/tls/tls.go
> +func LoadDTLS(c *Config) (*dtls.Config, error) {
Something like 

```go
func LoadTLSConfig(c *Config, protocol protocol) (interface{}, error) {
	if c.CertFile == "" || c.KeyFile == "" {
		return nil, nil
	}

	var config interface{}

	certificate, err := tls.LoadX509KeyPair(c.CertFile, c.KeyFile)
	if err != nil {
		return nil, errors.Join(errLoadCerts, err)
	}

	switch protocol {
	case TLS:
		config = &tls.Config{
			Certificates: []tls.Certificate{certificate},
		}
	case DTLS:
		config = &dtls.Config{
			Certificates: []tls.Certificate{certificate},
		}
	}

	// Loading Server CA file
	rootCA, err := loadCertFile(c.ServerCAFile)
	if err != nil {
		return nil, errors.Join(errLoadServerCA, err)
	}
	if len(rootCA) > 0 {
		switch protocol {
		case TLS:
			tlsConfig := config.(*tls.Config)
			if tlsConfig.RootCAs == nil {
				tlsConfig.RootCAs = x509.NewCertPool()
			}
			if !tlsConfig.RootCAs.AppendCertsFromPEM(rootCA) {
				return nil, errAppendCA
			}
		case DTLS:
			dtlsConfig := config.(*dtls.Config)
			if dtlsConfig.RootCAs == nil {
				dtlsConfig.RootCAs = x509.NewCertPool()
			}
			if !dtlsConfig.RootCAs.AppendCertsFromPEM(rootCA) {
				return nil, errAppendCA
			}
		}

	}

	// Loading Client CA File
	clientCA, err := loadCertFile(c.ClientCAFile)
	if err != nil {
		return nil, errors.Join(errLoadClientCA, err)
	}
	if len(clientCA) > 0 {
		switch protocol {
		case TLS:
			tlsConfig := config.(*tls.Config)
			if tlsConfig.ClientCAs == nil {
				tlsConfig.ClientCAs = x509.NewCertPool()
			}
			if !tlsConfig.ClientCAs.AppendCertsFromPEM(clientCA) {
				return nil, errAppendCA
			}
			tlsConfig.ClientAuth = tls.RequireAndVerifyClientCert
			if c.Validator != nil {
				tlsConfig.VerifyPeerCertificate = c.Validator
			}
		case DTLS:
			dtlsConfig := config.(*dtls.Config)
			if dtlsConfig.ClientCAs == nil {
				dtlsConfig.ClientCAs = x509.NewCertPool()
			}
			if !dtlsConfig.ClientCAs.AppendCertsFromPEM(clientCA) {
				return nil, errAppendCA
			}
			dtlsConfig.ClientAuth = dtls.RequireAndVerifyClientCert
			if c.Validator != nil {
				dtlsConfig.VerifyPeerCertificate = c.Validator
			}
		}
	}

	return config, nil
}
```

But I have realised it becomes too cryptic since there is a lot of type checks since we are returning an interface. You can revert to the initial implementation having DTLS and TLS separate functions

2024-04-26 08:20 UTC, arvindh123 commented on config.go
> +	DTLSConfig *dtls.Config
@dborovcanin @rodneyosodo 
Can we try to use Go Generics here ? 
Instead of having  TLS & DTLS  configuration, we can have single SecConfig, which can be TLS or DTLS. This can be achieveable through Go Generics

2024-04-26 08:35 UTC, rodneyosodo commented on config.go
> +	DTLSConfig *dtls.Config
Yes. This also applies to https://github.com/1998-felix/mproxy/blob/e2586a5f5c91407844af9ccd8e576bb009fd20a2/pkg/tls/tls.go#L25 and https://github.com/1998-felix/mproxy/blob/e2586a5f5c91407844af9ccd8e576bb009fd20a2/pkg/tls/tls.go#L75 since the functions are the almost the same

2024-04-26 09:17 UTC, dborovcanin commented on config.go
> +	DTLSConfig *dtls.Config
You can't have a generic type constraint as a type (i.e. you would need to use interface here, but you can use generics to DRY for Load config) like @rodneyosodo suggested.

2024-04-30 14:22 UTC, rodneyosodo requested changes
Also send a corrensponding PR to masgistrala for coap to use mproxy

2024-04-30 14:22 UTC, rodneyosodo commented on pkg/tls/tls.go
> +type SecConfig interface {
Let's Rename this to something like

```suggestion
type TLSConfig interface {
```

2024-04-30 14:22 UTC, rodneyosodo commented on pkg/tls/tls.go
> +func LoadSecConfig[sc SecConfig](c *Config, s sc) (sc, error) {
Same

2024-04-30 14:22 UTC, rodneyosodo commented on pkg/tls/tls.go
> +	errUnsupportedSec = errors.New("unsupported security configuration")
same

2024-04-30 14:22 UTC, rodneyosodo commented on pkg/coap/coap.go
> +func (p *Proxy) ListenDTLS(ctx context.Context) error {
Let's only have Listen then if the DTLSConfig is present we initialize `NewDTLSListener` same thing as mqtt and http

2024-05-09 10:11 UTC, arvindh123 commented
@1998-felix 
It will be great if we provide example scripts to test the coap server and client, like how we have for MQTT, WS, HTTP with documentation in readme.md.

2024-05-22 12:14 UTC, rodneyosodo requested changes

2024-05-22 13:05 UTC, WashingtonKK requested changes

2024-05-22 14:54 UTC, nyagamunene commented on README.md
> +This scripts can be used after changing the `MPROXY_COAP_WITHOUT_DTLS_TARGET` and `MPROXY_COAP_WITH_DTLS_TARGET` to a public coap server such as `coap://coap.me:5683`
You can also add mention you need coap-client installed to run this. `sudo apt-get install libcoap2-bin`
`

2024-05-23 14:55 UTC, 1998-felix commented on examples/client/coap/with_dtls.sh
> +coap-client -m post coap://${host}:${port}/${path} -e "${message}" -O 12,${content} -O 15,auth=${auth} \
the coap-cli doesnt currently support dtls

2024-05-24 13:27 UTC, nyagamunene commented
LGTM

2024-05-24 13:41 UTC, nyagamunene submitted a review, later dismissed

2025-09-03 12:50 UTC, dborovcanin commented on pkg/coap/coap.go
> +	"github.com/pion/dtls/v2"
Let's use the latest `v3`.

2025-09-03 13:07 UTC, dborovcanin commented on pkg/coap/coap.go
> +			p.upUDP(conn, buffer[:n])
Is this connections map needed? I.e. can we write it in such a way that each client is handled in their routine?

2025-09-04 15:15 UTC, felixgateru commented on pkg/coap/coap.go
> +			p.upUDP(conn, buffer[:n])
I have investigate a few iterations of the code but we still need some routing state. With plain UDP there’s no connection object to bind a client to a server socket, so the proxy must remember which client should receive which upstream reply otherwise we end up spawning unused routines.

2025-09-04 17:39 UTC, dborovcanin commented on pkg/coap/coap.go
> +			p.upUDP(conn, buffer[:n])
That's OK, but can we keep it in closure; in goroutine level, rather than in the map?

2025-09-05 07:42 UTC, dborovcanin commented on pkg/coap/coap.go
> +			p.upUDP(conn, buffer[:n])
@felixgateru This is something I have on mind:
```go
package main

import (
	"log"
	"net"
	"time"
)

func main() {
	listenAddr := ":9000"
	targetAddrStr := "example.com:12345"

	listener, err := net.ListenPacket("udp", listenAddr)
	if err != nil {
		log.Fatalf("Failed to listen on %s: %v", listenAddr, err)
	}
	defer listener.Close()
	log.Printf("UDP proxy listening on %s → %s", listenAddr, targetAddrStr)

	targetAddr, err := net.ResolveUDPAddr("udp", targetAddrStr)
	if err != nil {
		log.Fatalf("Failed to resolve target: %v", err)
	}

	buf := make([]byte, 64*1024)
	for {
		n, clientAddr, err := listener.ReadFrom(buf)
		if err != nil {
			log.Printf("Read error: %v", err)
			continue
		}

		data := append([]byte(nil), buf[:n]...)
		go handleClient(listener, clientAddr, targetAddr, data)
	}
}

func handleClient(listener net.PacketConn, clientAddr net.Addr, targetAddr *net.UDPAddr, firstPacket []byte) {
// Client is encapsulated in this function; there is no need for the map.
	targetConn, err := net.DialUDP("udp", nil, targetAddr)
	if err != nil {
		log.Printf("Dial target error: %v", err)
		return
	}
	defer targetConn.Close()

	// Send first client packet
	_, err = targetConn.Write(firstPacket)
	if err != nil {
		log.Printf("Write to target error: %v", err)
		return
	}

	// Channel to signal activity
	activity := make(chan struct{}, 1)

	// ->
	go func() {
		buf := make([]byte, 64*1024)
		for {
			targetConn.SetReadDeadline(time.Now().Add(30 * time.Second))
			n, _, err := targetConn.ReadFrom(buf)
			if err != nil {
				return // timeout or closed
			}
--------->           // Handle CoAP here to perform authorization.
			// Forward response
			_, err = listener.WriteTo(buf[:n], clientAddr)
			if err != nil {
				log.Printf("Write to client error: %v", err)
				return
			}
			select {
			case activity <- struct{}{}:
			default:
			}
		}
	}()

	// <-
	buf := make([]byte, 64*1024)
	for {
		listener.SetReadDeadline(time.Now().Add(30 * time.Second))
		n, addr, err := listener.ReadFrom(buf)
		if err != nil {
			return
		}
		if addr.String() != clientAddr.String() {
			// Ignore other clients
			continue
		}
		_, err = targetConn.Write(buf[:n])
		if err != nil {
			log.Printf("Write to target error: %v", err)
			return
		}
		select {
		case activity <- struct{}{}:
		default:
		}
	}
}
```
this is just the idea, not the exact implementation. Please check if Go CoAP lib can support something like this.

2025-09-05 14:10 UTC, dborovcanin requested changes

2025-09-05 14:10 UTC, dborovcanin commented on pkg/coap/coap.go
> +					p.mutex.Unlock()
Release lock before logging error.

2025-09-05 18:07 UTC, merged